### ISSUE TITLE
Checklist prior to any other discussion next week

### ISSUE THREAD

**Issue by gfon** [stefanosts/reporting#1]
@stefanosts  Before we start discussing other issues please:

- [ ]  να αλλάξεις τη δομή ειδικά στο κομμάτι του validation, να το κάνεις πιο κατανοητό, ότι έχει να κάνει με co2mpas pycsis μένει ότι έχει να κάνει με τα υπόλοιπα αναφέρεται/περιγράφεται (θα βοηθούσε ένα flow chart στην αρχή του κεφαλαίου) και οι υπόλοιπες λεπτομέρειες πάνε πίσω

- [ ]  να κλίσεις το κομμάτι του model description/validation

- [ ] να δουλέψεις  λίγο το κομμάτι τον αποτελεσμάτων γράφοντας ελεύθερα με δικά σου λόγια αυτά που θέλεις να μείνουν και ειδικότερα ορισμένα πράγματα για τα On road & plug ins, ας μην είναι τέλειο

- [ ] να ξαναγράψεις ριζικά το κομμάτι του novelty of the phd (1 σελίδα) με δικά σου λόγια, λέγοντας ακριβώς το γιατί είναι novel to phd! Επίσης να πεις ότι ως κομμάτι του phd έγραψες και τον κώδικα του πρώτου co2mpas που είναι ουσιαστικά η βάση του pycsis

- [ ] βάλε  με bullets τα δικά σου συμπεράσματα και follow up activity (τουλάχιστον με bullets)

- [ ] να  μη χρησιμοποιήσεις άλλο έτοιμο κείμενο, τα παραπάνω να γίνουν με νέο κείμενο δικό σου το οποίο θα είναι τουλάχιστον 12 σελίδες (θα το ελέγξω!).
